#version 450
layout(local_size_x=64)in;layout(set=0,binding=0,std430)buffer Data{vec4 values[];}data;layout(push_constant)uniform Push{vec4 p[8];}pc;
void main(){uint id=gl_GlobalInvocationID.x;if(id>=1024u)return;float x=float(id)/1023.;float clearcoat=.5+.5*sin(x*9.+pc.p[0].z);float transmission=.5+.5*cos(x*12.);float sheen=.5+.5*sin(x*19.);float anisotropy=abs(sin(x*27.));data.values[id]=vec4(clearcoat,transmission,sheen,anisotropy);}
